### PR TITLE
fix: add .js extensions to ESM imports via postbuild script

### PR DESCRIPTION
**Pull request by leecoder**
## Problem

OpenCode v1.14.21 bumped its embedded Bun runtime from 1.3.11 to 1.3.13 ([sst/opencode#23791](https://github.com/sst/opencode/pull/23791)), which enforces strict ESM module resolution. The compiled `dist/` files use extensionless relative imports (e.g. `from './plugin/config/schema'`) that Bun 1.3.13+ refuses to resolve, causing the plugin to fail to load:

```
Cannot find module '.../dist/plugin/config/schema' imported from .../dist/constants.js
```

This breaks the kiro provider entirely on OpenCode >= 1.14.21.

## Root Cause

`tsconfig.json` uses `"module": "Preserve"` with `"moduleResolution": "bundler"`, which emits extensionless imports. This worked on Bun 1.3.11 (lenient resolution) but fails on Bun 1.3.13+ (strict ESM).

## Solution

Add a postbuild script (`scripts/fix-esm-imports.mjs`) that automatically appends `.js` extensions to all relative imports in `dist/` after `tsc` compilation. The `build` script in `package.json` is updated to run it:

```
"build": "tsc -p tsconfig.build.json && node scripts/fix-esm-imports.mjs"
```

This approach requires zero changes to source code or tsconfig.

## Verification

- Build succeeds: 37/106 files patched, 0 extensionless imports remaining
- Node.js strict ESM import test passes
- No source code changes required

### CODE REVIEW

**Comment by tickernelz** [comment]
Thanks for the fix — this is useful for keeping the built package compatible with stricter ESM resolution in newer OpenCode/Bun runtimes.

Merged into master and included in the follow-up patch release: `v1.10.1`.

Verified locally before release:
- `npm run typecheck` passed
- `npm run build` passed
- `npm test` passed (8 tests)
- `npm audit` reports 0 vulnerabilities

Appreciate the contribution!
